### ISSUE TITLE
ASP.NET Core Dependency Injection

### ISSUE THREAD

**Issue by BillChirico** [cordialgerm/FluentCache#11]
Hello,

What would be the proper way to implement FluentCache into ASP.NET Core services?

I was thinking something like this, but it's throwing an error:
```csharp
services.AddMemoryCache();
services.AddSingleton<IMemoryCache>(new FluentIMemoryCache(IMemoryCache memoryCache));
```

**Comment by evan-rash** [comment]
What's the error?

**Comment by BillChirico** [comment]
@cordialgerm I ended up with `services.AddSingleton<ICache>(new FluentIMemoryCache(new MemoryCache(new MemoryCacheOptions())));` is this correct?

**Comment by evan-rash** [comment]
looks right to me
