### ISSUE TITLE
Support generics in Method CacheStrategy

### ISSUE THREAD

**Issue by adalbus** [cordialgerm/FluentCache#2]
Let's say we have a generic repository for multiple entities

`public interface IRepository<T> where T : IEntity
    {
        Task<IList<T>> GetAllAsync();
   }`

And implementation

`public class DocumentRepository<T> : IRepository<T>{...}`

Now, we want to retrieve a list of entities of type `Supplier` like this:

` IList<Supplier> suppliers = await this.cache.WithSource(this.supplierRepository).Method(c => c.GetAllAsync()).ExpireAfter(TimeSpan.FromMinutes(30)).GetValueAsync())`

The cache key will be something like 

> IRepository`1

The problem is that for other entities, the cache key will be the same, thus overwritting each other.

**Comment by evan-rash** [comment]
Good point. The cache key should start with `DocumentRepository<Supplier>`. Will add to next release

**Comment by adalbus** [comment]
Thank you very much @cordialgerm

**Comment by evan-rash** [comment]
To fix: enhance `ExpressionAnalyzer.CreateCacheStrategyFromMethod` and `ExpressionAnalyzer.CreateCacheStrategyFromMember` so that the region is based on the expression source object's `GetType()` (the concrete type) rather than the compile-time type (as those can be generic types)

**Comment by evan-rash** [comment]
@adalbus as a workaround you can add a `WithRegion("DoumentRepository<Supplier>")` call

**Comment by evan-rash** [comment]
fixed in v4.0.0.1 release
