### ISSUE TITLE
Support for Microsoft.Extensions.Caching.Memory

### ISSUE THREAD

**Issue by adalbus** [cordialgerm/FluentCache#3]
Many projects are moving away from System.Runtime.Caching towards Microsoft.Extensions.Caching.Memory.

This is the newest cross-platform library from ASP.NET Core for In-Memory local and distributed caching.

> https://github.com/aspnet/Caching

**Comment by evan-rash** [comment]
I'll take a look at what's needed

**Comment by evan-rash** [comment]
implemented in v4.0.0.1 release
