### ISSUE TITLE
There is a plan to sign the assembly?

### ISSUE THREAD

**Issue by MonDeveloper** [cordialgerm/FluentCache#5]
In order to use the library we had to remove the digital signature from our services, do you have plan to add the digital signature to the library?

**Comment by Nucs** [comment]
Consider using auto-signing tool that signs all output dlls right after building.

**Comment by igitur** [comment]
@MonDeveloper Are you really sure you need to sign?  Please read https://www.pedrolamas.com/2016/03/01/still-strong-naming-your-assemblies-you-do-know-its-2016-right/

**Comment by MonDeveloper** [comment]
@igitur Thanks for the interesting link, I'm not 100% agree but there are many ideas to let the re-evaluation process starts.

Specifically, I disagree to use the "unsigned" methodology to solve the dependency issue while the new csproj structure teamed with the semver-based nuget are a perfect combo to obtain all the libraries dependency graph under control.

A Good point is that the strong name doesn't provide a bit of real security.

**Comment by evan-rash** [comment]
I will sign the assembly in the next release

**Comment by evan-rash** [comment]
Should be fixed in v4.0.0.2
