### ISSUE TITLE
Collections

### ISSUE THREAD

**Issue by tariqayad** [cordialgerm/FluentCache#6]
Evan,

Will this cache collections, as expand collections and cache individual items?
What I mean is if had a method IEnumerable<Entity> GetAllItems()
would it cache each individual Entity in the collection so that when I call Entity GetItem, the item will be served from the cache?

**Comment by evan-rash** [comment]
There is support for a Bulk cache operation where each individual item in the response is cached by an individual ID. This works if the method you wish to cache is `ICollection<KeyValuePair<TKey,TItem>>> GetItems(ICollection<TKey> keys)`. Take a look at `BulkCacheStrategy` or `BulkCacheStrategyAsync`.

If you are not using the BulkCacheStrategy, then it will cache the entire return object from GetAllItems as a monolithic item

**Comment by increddibelly** [comment]
handling collections could be improved with an optional `Func<TItem, TKey> KeySelector` parameter to project an IEnumerable of Tkeys from the original request object.
