### ISSUE TITLE
Support for netframework projects.

### ISSUE THREAD

**Issue by Nucs** [cordialgerm/FluentCache#7]
The nuget packages for all the extensions are unusable if your project is a netframework project (and not a NetStandard project).
Many projects are legacy and are using the old project type, therefore cannot use the extensions.

It is easly fixed by adding `net45` to the project target frameworks and reuploading a new version onto nuget.

**Comment by prom3theu5** [comment]
Should be fine targeting full framework from version 4.6.1/2 upwards.
.net45 is kind of legacy now as 4.6 has been out since 2015!

**Comment by Nucs** [comment]
The difference between 4.5 and 4.6.1 are redundant except for the fact that the **library** doesn't support the "legacy" ones regardless the reason to why they are targeting 4.5.
All it takes is adding 4 lines.

**Comment by evan-rash** [comment]
@Nucs is there a way to add support for .NET 4.5 to a .NET Standard project? What are the 4 lines you're suggesting?

**Comment by prom3theu5** [comment]
For .net standard 1.1 - sure there is
But for .net standard 1.3 upwards, minimum full framework version starts at 4.6

There is a handy table on [here](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)

**Comment by evan-rash** [comment]
Ok, so I will change the FluentCache package to .NET Standard 1.1 so that .NET Framework 4.5 is supported

**Comment by prom3theu5** [comment]
I'm not sure it's worth the hassle tbh
Microsoft themselves dropped support (end of life essentially) 4.5 in January 2016.
It no longer gets security updates. People should upgrade their legacy projects.
Even Unity3d now supports .net standard 2.0

**Comment by evan-rash** [comment]
Should be fixed with 4.0.0.2
